#!/bin/sh

# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##  Important for running:
##
##  (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
##      noncompliant, but you have some other compliant shell such as ksh or
##      bash, then to run this script, type that shell name before the whole
##      command line, like:
##
##          ksh Gradle
##
##      Busybox and similar reduced shells will NOT work, because this script
##      requires all of these POSIX shell features:
##        * functions;
##        * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
##          «${var#prefix}», «${var%suffix}», and «$( cmd )»;
##        * compound commands having a testable exit status, especially «case»;
##        * various built-in commands including «command», «set», and «ulimit».
##
##  (2) This script was generated for a Gradle installation at
##      /opt/hostedtoolcache/gradle/8.9/x64
##      but we adapt to location where it's copied.
##
##  (3) Gradle requires a 64-bit JDK 17 or later.  We try to find one:
##      * We find one via the JAVA_HOME environment variable.
##      * We find one on the path.
##      * We fall back to using "java" from the path.
##
##  (4) This script supports the following environment variables:
##      * JAVA_HOME - location of a JDK home directory
##      * JAVA_OPTS - JVM options used by the Gradle daemon
##      * GRADLE_OPTS - JVM options used by the Gradle Daemon and the CLI
##      * GRADLE_USER_HOME - Gradle user home directory
##      * GRADLE_BUILD_MIRROR - Forces use of a non-standard JAR mirror to download dependencies. See doc for details.
##      * GRADLE_EXPERIMENTAL_SNAPSHOTS - Enable experimental snapshot updates
##      * GRADLE_WRAPPER_VERBOSE - Set to anything to enable verbose output for debugging
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%/*}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*-> }
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME/$link ;;
    esac
  done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='-Xmx64m -Xms64m'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    printf '%s\n' "$*" >&2
}

die () {
    printf '%s\n' "$*" >&2
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MINGW* )          msys=true    ;; #(
  MSYS* )           msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
  *)                ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case "$MAX_FD" in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case "$MAX_FD" in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                    #(
              *)    false ;;                            # don't convert
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        shift
        set -- "$@" "$arg"
    done
fi

# Collect all arguments for the java command:
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        $DEFAULT_JVM_OPTS \
        $JAVA_OPTS \
        $GRADLE_OPTS \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

exec "$JAVACMD" "$@"
